### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by noanti** [bwall/HashPump#13]
there is a memory leak bug in SHA1.cpp
![bug](https://cloud.githubusercontent.com/assets/6761874/7901209/1f455aa8-07af-11e5-9266-95fac80fe04a.png)

**Comment by bwall** [comment]
Thanks for bringing this to my attention.
I confirmed what you are seeing with valgrind.

Without making changes to how the functions are used (this actually affected all hash algos), I added deletes to anywhere that uses Extender->GenerateStretchedData for newSig.

Please feel free to confirm the fixes. :)

**Comment by noanti** [comment]
Nice :) 
Thanks for this tool.It is very convenient to use
