### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by heptathlon** [bwall/HashPump#18]
I tried the following:

```sh
# echo -n 'secretpublic' | sha1sum
2d7cd5ec556d1734267e2a188cbaa5c37efb1ce3  -

# The secret is 'secret' (length 6) and the public value is 'public' and I want to append 'PWNED'

# hashpump -s '2d7cd5ec556d1734267e2a188cbaa5c37efb1ce3' -d 'public' -a 'PWNED' -k 6
faf5e45f0946096a2165fa275799717248bf0304
public\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`PWNED

# echo -n 'secretpublicPWNED' | sha1sum
043008e450f195f6d67e028b02b68007684083af  -

# The hash produced by hashpump (faf5e45f0946096a2165fa275799717248bf0304) however is not 043008e450f195f6d67e028b02b68007684083af
```

**Comment by cebrusfs** [comment]
```

**Comment by nevmerzhitsky** [comment]
I faced with similar issue - generated by `hashpump` payload doesn't give ability to hack original payload. And when I tried to reproduce the error of @heptathlon I see next:

```bash
# echo -n 'secretpublic' | sha1sum
2d7cd5ec556d1734267e2a188cbaa5c37efb1ce3  -
# echo -n 'secretpublic\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`PWNED' | sha1sum
0192327f452b76bcac26b38b7bee39d7a5b8f2b5  -
```

Guys, may you help me just to achieve work of the code snippet of @cebrusfs ? :O

**Comment by bwall** [comment]
@nevmerzhitsky try hashing in a scripting language like python instead of on the command line, your version of echo may or may not be appending a new line

    >>> import hashlib
    >>> hashlib.sha1('secretpublic\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`PWNED').hexdigest()
    'faf5e45f0946096a2165fa275799717248bf0304'
